/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/products": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          created_at?: parameters["rowFilter.products.created_at"];
          edited_at?: parameters["rowFilter.products.edited_at"];
          name?: parameters["rowFilter.products.name"];
          short_description?: parameters["rowFilter.products.short_description"];
          long_description?: parameters["rowFilter.products.long_description"];
          /** category id reference */
          category_id?: parameters["rowFilter.products.category_id"];
          /** quanity of the product */
          quantity?: parameters["rowFilter.products.quantity"];
          /** expiry date of the product */
          expiry_date?: parameters["rowFilter.products.expiry_date"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** products */
          products?: definitions["products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          created_at?: parameters["rowFilter.products.created_at"];
          edited_at?: parameters["rowFilter.products.edited_at"];
          name?: parameters["rowFilter.products.name"];
          short_description?: parameters["rowFilter.products.short_description"];
          long_description?: parameters["rowFilter.products.long_description"];
          /** category id reference */
          category_id?: parameters["rowFilter.products.category_id"];
          /** quanity of the product */
          quantity?: parameters["rowFilter.products.quantity"];
          /** expiry date of the product */
          expiry_date?: parameters["rowFilter.products.expiry_date"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          created_at?: parameters["rowFilter.products.created_at"];
          edited_at?: parameters["rowFilter.products.edited_at"];
          name?: parameters["rowFilter.products.name"];
          short_description?: parameters["rowFilter.products.short_description"];
          long_description?: parameters["rowFilter.products.long_description"];
          /** category id reference */
          category_id?: parameters["rowFilter.products.category_id"];
          /** quanity of the product */
          quantity?: parameters["rowFilter.products.quantity"];
          /** expiry date of the product */
          expiry_date?: parameters["rowFilter.products.expiry_date"];
        };
        body: {
          /** products */
          products?: definitions["products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/categories": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.categories.id"];
          created_at?: parameters["rowFilter.categories.created_at"];
          edited_at?: parameters["rowFilter.categories.edited_at"];
          name?: parameters["rowFilter.categories.name"];
          short_description?: parameters["rowFilter.categories.short_description"];
          long_description?: parameters["rowFilter.categories.long_description"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["categories"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** categories */
          categories?: definitions["categories"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.categories.id"];
          created_at?: parameters["rowFilter.categories.created_at"];
          edited_at?: parameters["rowFilter.categories.edited_at"];
          name?: parameters["rowFilter.categories.name"];
          short_description?: parameters["rowFilter.categories.short_description"];
          long_description?: parameters["rowFilter.categories.long_description"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.categories.id"];
          created_at?: parameters["rowFilter.categories.created_at"];
          edited_at?: parameters["rowFilter.categories.edited_at"];
          name?: parameters["rowFilter.categories.name"];
          short_description?: parameters["rowFilter.categories.short_description"];
          long_description?: parameters["rowFilter.categories.long_description"];
        };
        body: {
          /** categories */
          categories?: definitions["categories"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description home inventory product entity */
  products: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    edited_at?: string;
    /** Format: text */
    name: string;
    /** Format: text */
    short_description: string;
    /** Format: text */
    long_description?: string;
    /**
     * Format: integer
     * @description category id reference
     *
     * Note:
     * This is a Foreign Key to `categories.id`.<fk table='categories' column='id'/>
     */
    category_id: number;
    /**
     * Format: smallint
     * @description quanity of the product
     */
    quantity: number;
    /**
     * Format: date
     * @description expiry date of the product
     */
    expiry_date: string;
  };
  /** @description categories used for filtering the */
  categories: {
    /**
     * Format: integer
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    edited_at?: string;
    /** Format: text */
    name: string;
    /** Format: text */
    short_description: string;
    /** Format: text */
    long_description?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description products */
  "body.products": definitions["products"];
  /** Format: bigint */
  "rowFilter.products.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.products.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.products.edited_at": string;
  /** Format: text */
  "rowFilter.products.name": string;
  /** Format: text */
  "rowFilter.products.short_description": string;
  /** Format: text */
  "rowFilter.products.long_description": string;
  /**
   * Format: integer
   * @description category id reference
   */
  "rowFilter.products.category_id": string;
  /**
   * Format: smallint
   * @description quanity of the product
   */
  "rowFilter.products.quantity": string;
  /**
   * Format: date
   * @description expiry date of the product
   */
  "rowFilter.products.expiry_date": string;
  /** @description categories */
  "body.categories": definitions["categories"];
  /** Format: integer */
  "rowFilter.categories.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.categories.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.categories.edited_at": string;
  /** Format: text */
  "rowFilter.categories.name": string;
  /** Format: text */
  "rowFilter.categories.short_description": string;
  /** Format: text */
  "rowFilter.categories.long_description": string;
}

export interface operations {}

export interface external {}
